/**
 * *****************************************************************************
 * Copyright or © or Copr. IETR/INSA: Maxime Pelcat, Jean-François Nezan,
 * Karol Desnos, Julien Heulot, Clément Guy, Yaset Oliva Venegas
 *
 * [mpelcat,jnezan,kdesnos,jheulot,cguy,yoliva]@insa-rennes.fr
 *
 * This software is a computer program whose purpose is to prototype
 * parallel applications.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 * ****************************************************************************
 */

#ifndef DDPG_H
#define DDPG_H

#include <spider.h>

#define N_PE_TYPE 1
#define N_CORE_TYPE_X86 1
#define N_PE (N_CORE_TYPE_X86)
#define SH_MEM_SIZE (0x04000000)

void initArchi();
void freeArchi();

#define N_FCT_DDPG 95
extern lrtFct ddpg_fcts[N_FCT_DDPG];

void init_ddpg(Param action_space_size = 3, Param bufferSize = 5000, Param hidden_size_0 = 400, Param hidden_size_1 = 300, Param sampleSize = 64, Param state_space_size = 6, Param value_space_size = 1, Param x_target = 3, Param y_target = 4, Param z_target = 2);
void free_ddpg();
std::map<lrtFct, std::map<const char *, PapifyConfig*>> get_ddpg_papifyConfigs();
void free_ddpg_papifyConfigs(std::map<lrtFct, std::map<const char *, PapifyConfig*>>& map);

enum class PEVirtID : std::uint32_t {
	CORE_CORE0 = 0,
}; 

enum class PEHardwareID : std::uint32_t {
	CORE_CORE0 = 0,
}; 

enum class PEType : std::uint32_t {
	CORE_TYPE_X86 = 0,
};

typedef enum{
	DDPG_ENVIRONMENT_FCT = 0,
	DDPG_TEMPORAL_DIFFERENCE_ERROR_FCT = 1,
	DDPG_GAUSSIANPOLICY_FCT = 2,
	DDPG_VALID_ACTOR_FCT = 3,
	DDPG_VALID_CRITIC_FCT = 4,
	DDPG_GEN_GAMMA_FCT = 5,
	DDPG_GEN_SIGMA_FCT = 6,
	DDPG_GEN_ACTOR_LEARNING_RATE_FCT = 7,
	DDPG_GEN_CRITIC_LEARNING_RATE_FCT = 8,
	DDPG_CLIPACTION_FCT = 9,
	DDPG_GEN_ENVIRONMENT_LIMITS_FCT = 10,
	DDPG_SET_FILLSIZE_FCT = 11,
	DDPG_INIT_STATE_FCT = 12,
	DDPG_END_STATE_FCT = 13,
	DDPG_GEN_TO_FCT = 14,
	DDPG_ACTOR_MLP_ACTIVATIONFUNCTION_0_FCT = 15,
	DDPG_ACTOR_MLP_VALID_MLP_FCT = 16,
	DDPG_ACTOR_MLP_OUTPUTACTIVATION_FCT = 17,
	DDPG_ACTOR_MLP_ACTIVATIONFUNCTION_1_FCT = 18,
	DDPG_ACTOR_MLP_OUTPUT_LAYER_COMPUTENEURON_FCT = 19,
	DDPG_ACTOR_MLP_HIDDEN_LAYER_0_COMPUTENEURON_FCT = 20,
	DDPG_ACTOR_MLP_HIDDEN_LAYER_1_COMPUTENEURON_FCT = 21,
	DDPG_FILL_BUFFER_SHUFFLE_FCT = 22,
	DDPG_TARGETACTOR_MLP_ACTIVATIONFUNCTION_0_FCT = 23,
	DDPG_TARGETACTOR_MLP_VALID_MLP_FCT = 24,
	DDPG_TARGETACTOR_MLP_OUTPUTACTIVATION_FCT = 25,
	DDPG_TARGETACTOR_MLP_ACTIVATIONFUNCTION_1_FCT = 26,
	DDPG_TARGETACTOR_MLP_OUTPUT_LAYER_COMPUTENEURON_FCT = 27,
	DDPG_TARGETACTOR_MLP_HIDDEN_LAYER_0_COMPUTENEURON_FCT = 28,
	DDPG_TARGETACTOR_MLP_HIDDEN_LAYER_1_COMPUTENEURON_FCT = 29,
	DDPG_TARGETCRITIC_MLP_ACTIVATIONFUNCTION_0_FCT = 30,
	DDPG_TARGETCRITIC_MLP_VALID_MLP_FCT = 31,
	DDPG_TARGETCRITIC_MLP_OUTPUTACTIVATION_FCT = 32,
	DDPG_TARGETCRITIC_MLP_ACTIVATIONFUNCTION_1_FCT = 33,
	DDPG_TARGETCRITIC_MLP_OUTPUT_LAYER_COMPUTENEURON_FCT = 34,
	DDPG_TARGETCRITIC_MLP_HIDDEN_LAYER_0_COMPUTENEURON_FCT = 35,
	DDPG_TARGETCRITIC_MLP_HIDDEN_LAYER_1_COMPUTENEURON_FCT = 36,
	DDPG_SET_TARGETACTOR_SETWEIGHTS_FCT = 37,
	DDPG_SET_TARGETACTOR_SETBIAS_FCT = 38,
	DDPG_SET_TARGETCRITIC_SETWEIGHTS_FCT = 39,
	DDPG_SET_TARGETCRITIC_SETBIAS_FCT = 40,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_GEN_EPSILON_FCT = 41,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_ADAMBETAS_FCT = 42,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_ADAMOUTPUT_OPTIMIZEWEIGHTS_FCT = 43,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_ADAMOUTPUT_OPTIMIZEBIAS_FCT = 44,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_ADAMHIDDEN_1_OPTIMIZEWEIGHTS_FCT = 45,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_ADAMHIDDEN_1_OPTIMIZEBIAS_FCT = 46,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_MLP_ACTIVATIONFUNCTION_0_FCT = 47,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_MLP_VALID_MLP_FCT = 48,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_MLP_OUTPUTACTIVATION_FCT = 49,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_MLP_ACTIVATIONFUNCTION_1_FCT = 50,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_MLP_OUTPUT_LAYER_COMPUTENEURON_FCT = 51,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_MLP_HIDDEN_LAYER_0_COMPUTENEURON_FCT = 52,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_MLP_HIDDEN_LAYER_1_COMPUTENEURON_FCT = 53,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_GRADIENTSHIDDEN_1_DERIVATIVE_FUNCTION_FCT = 54,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_GRADIENTSHIDDEN_1_BACKPROPAGATED_ERROR_FCT = 55,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_GRADIENTSHIDDEN_1_GRADIENTS_FCT = 56,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_GRADIENTSOUTPUT_GRADIENTS_FCT = 57,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_GRADIENTSOUTPUT_DERIVATIVE_FUNCTION_FCT = 58,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_GRADIENTSHIDDEN_0_DERIVATIVE_FUNCTION_FCT = 59,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_GRADIENTSHIDDEN_0_BACKPROPAGATED_ERROR_FCT = 60,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_GRADIENTSHIDDEN_0_GRADIENTS_FCT = 61,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_ADAMHIDDEN_0_OPTIMIZEWEIGHTS_FCT = 62,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_ADAMHIDDEN_0_OPTIMIZEBIAS_FCT = 63,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_CRITIC_ACTIVATIONFUNCTION_0_FCT = 64,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_CRITIC_VALID_MLP_FCT = 65,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_CRITIC_OUTPUTACTIVATION_FCT = 66,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_CRITIC_ACTIVATIONFUNCTION_1_FCT = 67,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_CRITIC_OUTPUT_LAYER_COMPUTENEURON_FCT = 68,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_CRITIC_HIDDEN_LAYER_0_COMPUTENEURON_FCT = 69,
	DDPG_UPDATE_NETWORKS_UPDATE_ACTOR_CRITIC_HIDDEN_LAYER_1_COMPUTENEURON_FCT = 70,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GEN_EPSILON_FCT = 71,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_ADAMBETAS_FCT = 72,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_ADAMOUTPUT_OPTIMIZEWEIGHTS_FCT = 73,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_ADAMOUTPUT_OPTIMIZEBIAS_FCT = 74,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_ADAMHIDDEN_1_OPTIMIZEWEIGHTS_FCT = 75,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_ADAMHIDDEN_1_OPTIMIZEBIAS_FCT = 76,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_MLP_ACTIVATIONFUNCTION_0_FCT = 77,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_MLP_VALID_MLP_FCT = 78,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_MLP_OUTPUTACTIVATION_FCT = 79,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_MLP_ACTIVATIONFUNCTION_1_FCT = 80,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_MLP_OUTPUT_LAYER_COMPUTENEURON_FCT = 81,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_MLP_HIDDEN_LAYER_0_COMPUTENEURON_FCT = 82,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_MLP_HIDDEN_LAYER_1_COMPUTENEURON_FCT = 83,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GRADIENTSHIDDEN_1_DERIVATIVE_FUNCTION_FCT = 84,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GRADIENTSHIDDEN_1_BACKPROPAGATED_ERROR_FCT = 85,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GRADIENTSHIDDEN_1_GRADIENTS_FCT = 86,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GRADIENTSOUTPUT_OUTPUT_ERROR_FCT = 87,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GRADIENTSOUTPUT_GRADIENTS_FCT = 88,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GRADIENTSOUTPUT_DERIVATIVE_FUNCTION_FCT = 89,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GRADIENTSHIDDEN_0_DERIVATIVE_FUNCTION_FCT = 90,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GRADIENTSHIDDEN_0_BACKPROPAGATED_ERROR_FCT = 91,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_GRADIENTSHIDDEN_0_GRADIENTS_FCT = 92,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_ADAMHIDDEN_0_OPTIMIZEWEIGHTS_FCT = 93,
	DDPG_UPDATE_NETWORKS_UPDATE_CRITIC_ADAMHIDDEN_0_OPTIMIZEBIAS_FCT = 94,
} FctIxs;

#endif//DDPG_H
