/**
 * @file Core0.c
 * @generated by CPrinter
 * @date Fri Nov 03 10:30:06 CET 2017
 * 
 * Code generated for processing element Core0 (ID=0).
 */

#include "../include/x86.h"

// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;

// Core Global Definitions
char Shared[2500]; //  size:= 2500*char
char *const FIFO_Head_Environment_end_st__0 = (char*) (Shared+2084);  // FIFO_Head_Environment_end_state_observation > Actor_MLP_action_predictor_Hidden_layer_br_input_init_input size:= 12*char
char *const FIFO_Head_Actor_MLP_action_p__1 = (char*) (Shared+2336);  // FIFO_Head_Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_end_bias_out1_20_0 > Actor_MLP_action_predictor_weights_hidden_weightGen_init_bias_in size:= 80*char
char *const FIFO_Head_Actor_MLP_action_p__0 = (char*) (Shared+2096);  // FIFO_Head_Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_end_weights_out1_0_0 > Actor_MLP_action_predictor_weights_hidden_weightGen_init_weights_in size:= 240*char
char *const FIFO_Head_Actor_MLP_action_p__3 = (char*) (Shared+2496);  // FIFO_Head_Actor_MLP_action_predictor_weights_output_BroadcastBiasGen_end_bias_out1_1_0 > Actor_MLP_action_predictor_weights_output_weightGen_init_bias_in size:= 4*char
char *const FIFO_Head_Actor_MLP_action_p__2 = (char*) (Shared+2416);  // FIFO_Head_Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen_end_weights_out1_0_0 > Actor_MLP_action_predictor_weights_output_weightGen_init_weights_in size:= 80*char
char *const FIFO_Head_broadcastState_end__0 = (char*) (Shared+2076);  // FIFO_Head_broadcastState_end_state_out1_2_0 > Environment_init_state_angular_in size:= 8*char
char *const Environment_init_state_angul__0 = (char*) (Shared+0);  // Environment_init_state_angular_in > Environment size:= 8*char
char *const Actor_MLP_action_predictor_H__0 = (char*) (Shared+8);  // Actor_MLP_action_predictor_Hidden_layer_br_input_init_input > Actor_MLP_action_predictor_Hidden_layer_br_input size:= 12*char
char *const Actor_MLP_action_predictor_w__0 = (char*) (Shared+20);  // Actor_MLP_action_predictor_weights_hidden_weightGen_init_weights_in > Actor_MLP_action_predictor_weights_hidden_weightGen size:= 240*char
char *const Actor_MLP_action_predictor_w__1 = (char*) (Shared+260);  // Actor_MLP_action_predictor_weights_hidden_weightGen_init_bias_in > Actor_MLP_action_predictor_weights_hidden_weightGen size:= 80*char
char *const Actor_MLP_action_predictor_w__2 = (char*) (Shared+340);  // Actor_MLP_action_predictor_weights_output_weightGen_init_weights_in > Actor_MLP_action_predictor_weights_output_weightGen size:= 80*char
char *const Actor_MLP_action_predictor_w__3 = (char*) (Shared+420);  // Actor_MLP_action_predictor_weights_output_weightGen_init_bias_in > Actor_MLP_action_predictor_weights_output_weightGen size:= 4*char
char *const Actor_MLP_action_predictor_H__1 = (char*) (Shared+424);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_0 size:= 12*char
char *const Actor_MLP_action_predictor_H__2 = (char*) (Shared+436);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_1 size:= 12*char
char *const Actor_MLP_action_predictor_H__3 = (char*) (Shared+448);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_2 size:= 12*char
char *const Actor_MLP_action_predictor_H__4 = (char*) (Shared+460);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_3 size:= 12*char
char *const Actor_MLP_action_predictor_H__5 = (char*) (Shared+472);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_4 size:= 12*char
char *const Actor_MLP_action_predictor_H__6 = (char*) (Shared+484);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_5 size:= 12*char
char *const Actor_MLP_action_predictor_H__7 = (char*) (Shared+496);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_6 size:= 12*char
char *const Actor_MLP_action_predictor_H__8 = (char*) (Shared+508);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_7 size:= 12*char
char *const Actor_MLP_action_predictor_H__9 = (char*) (Shared+520);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_8 size:= 12*char
char *const Actor_MLP_action_predictor_H__10 = (char*) (Shared+532);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_9 size:= 12*char
char *const Actor_MLP_action_predictor_H__11 = (char*) (Shared+544);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_10 size:= 12*char
char *const Actor_MLP_action_predictor_H__12 = (char*) (Shared+556);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_11 size:= 12*char
char *const Actor_MLP_action_predictor_H__13 = (char*) (Shared+568);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_12 size:= 12*char
char *const Actor_MLP_action_predictor_H__14 = (char*) (Shared+580);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_13 size:= 12*char
char *const Actor_MLP_action_predictor_H__15 = (char*) (Shared+592);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_14 size:= 12*char
char *const Actor_MLP_action_predictor_H__16 = (char*) (Shared+604);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_15 size:= 12*char
char *const Actor_MLP_action_predictor_H__17 = (char*) (Shared+616);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_16 size:= 12*char
char *const Actor_MLP_action_predictor_H__18 = (char*) (Shared+628);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_17 size:= 12*char
char *const Actor_MLP_action_predictor_H__19 = (char*) (Shared+640);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_18 size:= 12*char
char *const Actor_MLP_action_predictor_H__20 = (char*) (Shared+652);  // Actor_MLP_action_predictor_Hidden_layer_br_input > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_19 size:= 12*char
char *const Actor_MLP_action_predictor_w__4 = (char*) (Shared+664);  // Actor_MLP_action_predictor_weights_hidden_weightGen > Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen size:= 240*char
char *const Actor_MLP_action_predictor_w__5 = (char*) (Shared+904);  // Actor_MLP_action_predictor_weights_hidden_weightGen > Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen size:= 80*char
char *const Actor_MLP_action_predictor_w__6 = (char*) (Shared+984);  // Actor_MLP_action_predictor_weights_output_weightGen > Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen size:= 80*char
char *const Actor_MLP_action_predictor_w__7 = (char*) (Shared+1064);  // Actor_MLP_action_predictor_weights_output_weightGen > Actor_MLP_action_predictor_weights_output_BroadcastBiasGen size:= 4*char
char *const Actor_MLP_action_predictor_w__8 = (char*) (Shared+1068);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_0 size:= 12*char
char *const Actor_MLP_action_predictor_w__9 = (char*) (Shared+1080);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_1 size:= 12*char
char *const Actor_MLP_action_predictor_w__10 = (char*) (Shared+1092);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_2 size:= 12*char
char *const Actor_MLP_action_predictor_w__11 = (char*) (Shared+1104);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_3 size:= 12*char
char *const Actor_MLP_action_predictor_w__12 = (char*) (Shared+1116);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_4 size:= 12*char
char *const Actor_MLP_action_predictor_w__13 = (char*) (Shared+1128);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_5 size:= 12*char
char *const Actor_MLP_action_predictor_w__14 = (char*) (Shared+1140);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_6 size:= 12*char
char *const Actor_MLP_action_predictor_w__15 = (char*) (Shared+1152);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_7 size:= 12*char
char *const Actor_MLP_action_predictor_w__16 = (char*) (Shared+1164);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_8 size:= 12*char
char *const Actor_MLP_action_predictor_w__17 = (char*) (Shared+1176);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_9 size:= 12*char
char *const Actor_MLP_action_predictor_w__18 = (char*) (Shared+1188);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_10 size:= 12*char
char *const Actor_MLP_action_predictor_w__19 = (char*) (Shared+1200);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_11 size:= 12*char
char *const Actor_MLP_action_predictor_w__20 = (char*) (Shared+1212);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_12 size:= 12*char
char *const Actor_MLP_action_predictor_w__21 = (char*) (Shared+1224);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_13 size:= 12*char
char *const Actor_MLP_action_predictor_w__22 = (char*) (Shared+1236);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_14 size:= 12*char
char *const Actor_MLP_action_predictor_w__23 = (char*) (Shared+1248);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_15 size:= 12*char
char *const Actor_MLP_action_predictor_w__24 = (char*) (Shared+1260);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_16 size:= 12*char
char *const Actor_MLP_action_predictor_w__25 = (char*) (Shared+1272);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_17 size:= 12*char
char *const Actor_MLP_action_predictor_w__26 = (char*) (Shared+1284);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_18 size:= 12*char
char *const Actor_MLP_action_predictor_w__27 = (char*) (Shared+1296);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_19 size:= 12*char
char *const Actor_MLP_action_predictor_w__28 = (char*) (Shared+1308);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen > Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_end_weights_out1_0_0 size:= 240*char
char *const Actor_MLP_action_predictor_w__29 = (char*) (Shared+1548);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_0 size:= 4*char
char *const Actor_MLP_action_predictor_w__30 = (char*) (Shared+1552);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_1 size:= 4*char
char *const Actor_MLP_action_predictor_w__31 = (char*) (Shared+1556);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_2 size:= 4*char
char *const Actor_MLP_action_predictor_w__32 = (char*) (Shared+1560);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_3 size:= 4*char
char *const Actor_MLP_action_predictor_w__33 = (char*) (Shared+1564);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_4 size:= 4*char
char *const Actor_MLP_action_predictor_w__34 = (char*) (Shared+1568);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_5 size:= 4*char
char *const Actor_MLP_action_predictor_w__35 = (char*) (Shared+1572);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_6 size:= 4*char
char *const Actor_MLP_action_predictor_w__36 = (char*) (Shared+1576);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_7 size:= 4*char
char *const Actor_MLP_action_predictor_w__37 = (char*) (Shared+1580);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_8 size:= 4*char
char *const Actor_MLP_action_predictor_w__38 = (char*) (Shared+1584);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_9 size:= 4*char
char *const Actor_MLP_action_predictor_w__39 = (char*) (Shared+1588);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_10 size:= 4*char
char *const Actor_MLP_action_predictor_w__40 = (char*) (Shared+1592);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_11 size:= 4*char
char *const Actor_MLP_action_predictor_w__41 = (char*) (Shared+1596);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_12 size:= 4*char
char *const Actor_MLP_action_predictor_w__42 = (char*) (Shared+1600);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_13 size:= 4*char
char *const Actor_MLP_action_predictor_w__43 = (char*) (Shared+1604);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_14 size:= 4*char
char *const Actor_MLP_action_predictor_w__44 = (char*) (Shared+1608);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_15 size:= 4*char
char *const Actor_MLP_action_predictor_w__45 = (char*) (Shared+1612);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_16 size:= 4*char
char *const Actor_MLP_action_predictor_w__46 = (char*) (Shared+1616);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_17 size:= 4*char
char *const Actor_MLP_action_predictor_w__47 = (char*) (Shared+1620);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_18 size:= 4*char
char *const Actor_MLP_action_predictor_w__48 = (char*) (Shared+1624);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_19 size:= 4*char
char *const Actor_MLP_action_predictor_w__49 = (char*) (Shared+1628);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen > Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_end_bias_out1_20_0 size:= 80*char
char *const Actor_MLP_action_predictor_w__50 = (char*) (Shared+1708);  // Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen > Actor_MLP_action_predictor_Output_layer_computeNeuron size:= 80*char
char *const Actor_MLP_action_predictor_w__51 = (char*) (Shared+1788);  // Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen > Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen_end_weights_out1_0_0 size:= 80*char
char *const Actor_MLP_action_predictor_w__52 = (char*) (Shared+1868);  // Actor_MLP_action_predictor_weights_output_BroadcastBiasGen > Actor_MLP_action_predictor_Output_layer_computeNeuron size:= 4*char
char *const Actor_MLP_action_predictor_w__53 = (char*) (Shared+1872);  // Actor_MLP_action_predictor_weights_output_BroadcastBiasGen > Actor_MLP_action_predictor_weights_output_BroadcastBiasGen_end_bias_out1_1_0 size:= 4*char
char *const Actor_MLP_action_predictor_H__21 = (char*) (Shared+1876);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_0 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__22 = (char*) (Shared+1880);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_1 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__23 = (char*) (Shared+1884);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_2 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__24 = (char*) (Shared+1888);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_3 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__25 = (char*) (Shared+1892);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_4 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__26 = (char*) (Shared+1896);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_5 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__27 = (char*) (Shared+1900);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_6 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__28 = (char*) (Shared+1904);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_7 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__29 = (char*) (Shared+1908);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_8 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__30 = (char*) (Shared+1912);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_9 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__31 = (char*) (Shared+1916);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_10 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__32 = (char*) (Shared+1920);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_11 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__33 = (char*) (Shared+1924);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_12 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__34 = (char*) (Shared+1928);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_13 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__35 = (char*) (Shared+1932);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_14 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__36 = (char*) (Shared+1936);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_15 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__37 = (char*) (Shared+1940);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_16 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__38 = (char*) (Shared+1944);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_17 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__39 = (char*) (Shared+1948);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_18 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const Actor_MLP_action_predictor_H__40 = (char*) (Shared+1952);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_19 > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 4*char
char *const implode_Actor_MLP_action_pre__0 = (char*) (Shared+1956);  // implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input > Actor_MLP_action_predictor_Output_layer_computeNeuron size:= 80*char
char *const Actor_MLP_action_predictor_O__0 = (char*) (Shared+2036);  // Actor_MLP_action_predictor_Output_layer_computeNeuron > Environment size:= 4*char
char *const Environment__broadcastState__0 = (char*) (Shared+2040);  // Environment > broadcastState size:= 8*char
char *const Environment__Environment_end__0 = (char*) (Shared+2048);  // Environment > Environment_end_state_observation size:= 12*char
char *const broadcastState__renderEnv__0 = (char*) (Shared+2060);  // broadcastState > renderEnv size:= 8*char
char *const broadcastState__broadcastSta__0 = (char*) (Shared+2068);  // broadcastState > broadcastState_end_state_out1_2_0 size:= 8*char
float *const init_out__state_angular_in__0 = (float*) (Shared+0);  // Environment_init_state_angular_in_init_out > Environment_state_angular_in size:= 2*float
float *const init_out__input__0 = (float*) (Shared+8);  // Actor_MLP_action_predictor_Hidden_layer_br_input_init_input_init_out > Actor_MLP_action_predictor_Hidden_layer_br_input_input size:= 3*float
float *const init_out__weights_in__0 = (float*) (Shared+20);  // Actor_MLP_action_predictor_weights_hidden_weightGen_init_weights_in_init_out > Actor_MLP_action_predictor_weights_hidden_weightGen_weights_in size:= 60*float
float *const init_out__bias_in__0 = (float*) (Shared+260);  // Actor_MLP_action_predictor_weights_hidden_weightGen_init_bias_in_init_out > Actor_MLP_action_predictor_weights_hidden_weightGen_bias_in size:= 20*float
float *const init_out__weights_in__1 = (float*) (Shared+340);  // Actor_MLP_action_predictor_weights_output_weightGen_init_weights_in_init_out > Actor_MLP_action_predictor_weights_output_weightGen_weights_in size:= 20*float
float *const init_out__bias_in__1 = (float*) (Shared+420);  // Actor_MLP_action_predictor_weights_output_weightGen_init_bias_in_init_out > Actor_MLP_action_predictor_weights_output_weightGen_bias_in size:= 1*float
float *const input_0_0__input__0 = (float*) (Shared+424);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_0 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_0_input size:= 3*float
float *const input_0_3__input__0 = (float*) (Shared+436);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_3 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_1_input size:= 3*float
float *const input_0_6__input__0 = (float*) (Shared+448);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_6 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_2_input size:= 3*float
float *const input_0_9__input__0 = (float*) (Shared+460);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_9 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_3_input size:= 3*float
float *const input_0_12__input__0 = (float*) (Shared+472);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_12 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_4_input size:= 3*float
float *const input_0_15__input__0 = (float*) (Shared+484);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_15 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_5_input size:= 3*float
float *const input_0_18__input__0 = (float*) (Shared+496);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_18 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_6_input size:= 3*float
float *const input_0_21__input__0 = (float*) (Shared+508);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_21 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_7_input size:= 3*float
float *const input_0_24__input__0 = (float*) (Shared+520);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_24 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_8_input size:= 3*float
float *const input_0_27__input__0 = (float*) (Shared+532);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_27 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_9_input size:= 3*float
float *const input_0_30__input__0 = (float*) (Shared+544);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_30 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_10_input size:= 3*float
float *const input_0_33__input__0 = (float*) (Shared+556);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_33 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_11_input size:= 3*float
float *const input_0_36__input__0 = (float*) (Shared+568);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_36 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_12_input size:= 3*float
float *const input_0_39__input__0 = (float*) (Shared+580);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_39 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_13_input size:= 3*float
float *const input_0_42__input__0 = (float*) (Shared+592);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_42 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_14_input size:= 3*float
float *const input_0_45__input__0 = (float*) (Shared+604);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_45 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_15_input size:= 3*float
float *const input_0_48__input__0 = (float*) (Shared+616);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_48 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_16_input size:= 3*float
float *const input_0_51__input__0 = (float*) (Shared+628);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_51 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_17_input size:= 3*float
float *const input_0_54__input__0 = (float*) (Shared+640);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_54 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_18_input size:= 3*float
float *const input_0_57__input__0 = (float*) (Shared+652);  // Actor_MLP_action_predictor_Hidden_layer_br_input_input_0_57 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_19_input size:= 3*float
float *const weights_out__weights_in__0 = (float*) (Shared+664);  // Actor_MLP_action_predictor_weights_hidden_weightGen_weights_out > Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_in size:= 60*float
float *const bias_out__bias_in__0 = (float*) (Shared+904);  // Actor_MLP_action_predictor_weights_hidden_weightGen_bias_out > Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_in size:= 20*float
float *const weights_out__weights_in__1 = (float*) (Shared+984);  // Actor_MLP_action_predictor_weights_output_weightGen_weights_out > Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen_weights_in size:= 20*float
float *const bias_out__bias_in__1 = (float*) (Shared+1064);  // Actor_MLP_action_predictor_weights_output_weightGen_bias_out > Actor_MLP_action_predictor_weights_output_BroadcastBiasGen_bias_in size:= 1*float
float *const weights_out0_60_0__weights__0 = (float*) (Shared+1068);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_0 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_0_weights size:= 3*float
float *const weights_out0_60_3__weights__0 = (float*) (Shared+1080);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_3 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_1_weights size:= 3*float
float *const weights_out0_60_6__weights__0 = (float*) (Shared+1092);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_6 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_2_weights size:= 3*float
float *const weights_out0_60_9__weights__0 = (float*) (Shared+1104);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_9 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_3_weights size:= 3*float
float *const weights_out0_60_12__weights__0 = (float*) (Shared+1116);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_12 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_4_weights size:= 3*float
float *const weights_out0_60_15__weights__0 = (float*) (Shared+1128);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_15 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_5_weights size:= 3*float
float *const weights_out0_60_18__weights__0 = (float*) (Shared+1140);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_18 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_6_weights size:= 3*float
float *const weights_out0_60_21__weights__0 = (float*) (Shared+1152);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_21 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_7_weights size:= 3*float
float *const weights_out0_60_24__weights__0 = (float*) (Shared+1164);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_24 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_8_weights size:= 3*float
float *const weights_out0_60_27__weights__0 = (float*) (Shared+1176);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_27 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_9_weights size:= 3*float
float *const weights_out0_60_30__weights__0 = (float*) (Shared+1188);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_30 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_10_weights size:= 3*float
float *const weights_out0_60_33__weights__0 = (float*) (Shared+1200);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_33 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_11_weights size:= 3*float
float *const weights_out0_60_36__weights__0 = (float*) (Shared+1212);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_36 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_12_weights size:= 3*float
float *const weights_out0_60_39__weights__0 = (float*) (Shared+1224);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_39 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_13_weights size:= 3*float
float *const weights_out0_60_42__weights__0 = (float*) (Shared+1236);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_42 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_14_weights size:= 3*float
float *const weights_out0_60_45__weights__0 = (float*) (Shared+1248);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_45 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_15_weights size:= 3*float
float *const weights_out0_60_48__weights__0 = (float*) (Shared+1260);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_48 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_16_weights size:= 3*float
float *const weights_out0_60_51__weights__0 = (float*) (Shared+1272);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_51 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_17_weights size:= 3*float
float *const weights_out0_60_54__weights__0 = (float*) (Shared+1284);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_54 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_18_weights size:= 3*float
float *const weights_out0_60_57__weights__0 = (float*) (Shared+1296);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out0_60_57 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_19_weights size:= 3*float
float *const weights_out1_0_0__end_in__0 = (float*) (Shared+1308);  // Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_weights_out1_0_0 > Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen_end_weights_out1_0_0_end_in size:= 60*float
float *const bias_out0_0_0__bias_values__0 = (float*) (Shared+1548);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_0 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_0_bias_values size:= 1*float
float *const bias_out0_0_1__bias_values__0 = (float*) (Shared+1552);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_1 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_1_bias_values size:= 1*float
float *const bias_out0_0_2__bias_values__0 = (float*) (Shared+1556);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_2 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_2_bias_values size:= 1*float
float *const bias_out0_0_3__bias_values__0 = (float*) (Shared+1560);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_3 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_3_bias_values size:= 1*float
float *const bias_out0_0_4__bias_values__0 = (float*) (Shared+1564);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_4 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_4_bias_values size:= 1*float
float *const bias_out0_0_5__bias_values__0 = (float*) (Shared+1568);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_5 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_5_bias_values size:= 1*float
float *const bias_out0_0_6__bias_values__0 = (float*) (Shared+1572);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_6 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_6_bias_values size:= 1*float
float *const bias_out0_0_7__bias_values__0 = (float*) (Shared+1576);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_7 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_7_bias_values size:= 1*float
float *const bias_out0_0_8__bias_values__0 = (float*) (Shared+1580);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_8 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_8_bias_values size:= 1*float
float *const bias_out0_0_9__bias_values__0 = (float*) (Shared+1584);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_9 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_9_bias_values size:= 1*float
float *const bias_out0_0_10__bias_values__0 = (float*) (Shared+1588);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_10 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_10_bias_values size:= 1*float
float *const bias_out0_0_11__bias_values__0 = (float*) (Shared+1592);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_11 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_11_bias_values size:= 1*float
float *const bias_out0_0_12__bias_values__0 = (float*) (Shared+1596);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_12 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_12_bias_values size:= 1*float
float *const bias_out0_0_13__bias_values__0 = (float*) (Shared+1600);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_13 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_13_bias_values size:= 1*float
float *const bias_out0_0_14__bias_values__0 = (float*) (Shared+1604);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_14 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_14_bias_values size:= 1*float
float *const bias_out0_0_15__bias_values__0 = (float*) (Shared+1608);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_15 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_15_bias_values size:= 1*float
float *const bias_out0_0_16__bias_values__0 = (float*) (Shared+1612);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_16 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_16_bias_values size:= 1*float
float *const bias_out0_0_17__bias_values__0 = (float*) (Shared+1616);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_17 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_17_bias_values size:= 1*float
float *const bias_out0_0_18__bias_values__0 = (float*) (Shared+1620);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_18 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_18_bias_values size:= 1*float
float *const bias_out0_0_19__bias_values__0 = (float*) (Shared+1624);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out0_0_19 > Actor_MLP_action_predictor_Hidden_layer_computeNeuron_19_bias_values size:= 1*float
float *const bias_out1_20_0__end_in__0 = (float*) (Shared+1628);  // Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_bias_out1_20_0 > Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen_end_bias_out1_20_0_end_in size:= 20*float
float *const weights_out0_20_0__weights__0 = (float*) (Shared+1708);  // Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen_weights_out0_20_0 > Actor_MLP_action_predictor_Output_layer_computeNeuron_weights size:= 20*float
float *const weights_out1_0_0__end_in__1 = (float*) (Shared+1788);  // Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen_weights_out1_0_0 > Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen_end_weights_out1_0_0_end_in size:= 20*float
float *const bias_out0_0_0__bias_values__1 = (float*) (Shared+1868);  // Actor_MLP_action_predictor_weights_output_BroadcastBiasGen_bias_out0_0_0 > Actor_MLP_action_predictor_Output_layer_computeNeuron_bias_values size:= 1*float
float *const bias_out1_1_0__end_in__0 = (float*) (Shared+1872);  // Actor_MLP_action_predictor_weights_output_BroadcastBiasGen_bias_out1_1_0 > Actor_MLP_action_predictor_weights_output_BroadcastBiasGen_end_bias_out1_1_0_end_in size:= 1*float
float *const output__input_0__0 = (float*) (Shared+1876);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_0_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_0 size:= 1*float
float *const output__input_1__0 = (float*) (Shared+1880);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_1_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_1 size:= 1*float
float *const output__input_2__0 = (float*) (Shared+1884);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_2_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_2 size:= 1*float
float *const output__input_3__0 = (float*) (Shared+1888);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_3_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_3 size:= 1*float
float *const output__input_4__0 = (float*) (Shared+1892);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_4_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_4 size:= 1*float
float *const output__input_5__0 = (float*) (Shared+1896);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_5_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_5 size:= 1*float
float *const output__input_6__0 = (float*) (Shared+1900);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_6_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_6 size:= 1*float
float *const output__input_7__0 = (float*) (Shared+1904);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_7_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_7 size:= 1*float
float *const output__input_8__0 = (float*) (Shared+1908);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_8_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_8 size:= 1*float
float *const output__input_9__0 = (float*) (Shared+1912);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_9_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_9 size:= 1*float
float *const output__input_10__0 = (float*) (Shared+1916);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_10_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_10 size:= 1*float
float *const output__input_11__0 = (float*) (Shared+1920);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_11_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_11 size:= 1*float
float *const output__input_12__0 = (float*) (Shared+1924);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_12_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_12 size:= 1*float
float *const output__input_13__0 = (float*) (Shared+1928);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_13_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_13 size:= 1*float
float *const output__input_14__0 = (float*) (Shared+1932);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_14_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_14 size:= 1*float
float *const output__input_15__0 = (float*) (Shared+1936);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_15_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_15 size:= 1*float
float *const output__input_16__0 = (float*) (Shared+1940);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_16_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_16 size:= 1*float
float *const output__input_17__0 = (float*) (Shared+1944);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_17_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_17 size:= 1*float
float *const output__input_18__0 = (float*) (Shared+1948);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_18_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_18 size:= 1*float
float *const output__input_19__0 = (float*) (Shared+1952);  // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_19_output > implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_input_19 size:= 1*float
float *const output__input__0 = (float*) (Shared+1956);  // implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input_output > Actor_MLP_action_predictor_Output_layer_computeNeuron_input size:= 20*float
float *const output__input_actions__0 = (float*) (Shared+2036);  // Actor_MLP_action_predictor_Output_layer_computeNeuron_output > Environment_input_actions size:= 1*float
float *const state_angular_out__state__0 = (float*) (Shared+2040);  // Environment_state_angular_out > broadcastState_state size:= 2*float
float *const state_observation__end_in__0 = (float*) (Shared+2048);  // Environment_state_observation > Environment_end_state_observation_end_in size:= 3*float
float *const state_out0_0_0__state__0 = (float*) (Shared+2060);  // broadcastState_state_out0_0_0 > renderEnv_state size:= 2*float
float *const state_out1_2_0__end_in__0 = (float*) (Shared+2068);  // broadcastState_state_out1_2_0 > broadcastState_end_state_out1_2_0_end_in size:= 2*float

void *computationThread_Core0(void *arg){
	// Initialisation(s)
	fifoInit(FIFO_Head_Environment_end_st__0, 12*sizeof(char), NULL, 0);
	fifoInit(FIFO_Head_Actor_MLP_action_p__1, 80*sizeof(char), NULL, 0);
	fifoInit(FIFO_Head_Actor_MLP_action_p__0, 240*sizeof(char), NULL, 0);
	fifoInit(FIFO_Head_Actor_MLP_action_p__3, 4*sizeof(char), NULL, 0);
	fifoInit(FIFO_Head_Actor_MLP_action_p__2, 80*sizeof(char), NULL, 0);
	fifoInit(FIFO_Head_broadcastState_end__0, 8*sizeof(char), NULL, 0);
	renderInit(); // renderEnv

    envInit((float*)FIFO_Head_broadcastState_end__0, (float*)FIFO_Head_Environment_end_st__0);
    actorWeightGenInit(0, (float*)FIFO_Head_Actor_MLP_action_p__0, (float*)FIFO_Head_Actor_MLP_action_p__1);
    actorWeightGenInit(1, (float*)FIFO_Head_Actor_MLP_action_p__2, (float*)FIFO_Head_Actor_MLP_action_p__3);

	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		fifoPop(init_out__input__0, FIFO_Head_Environment_end_st__0, 12*sizeof(char), NULL, 0);
		fifoPop(init_out__bias_in__0, FIFO_Head_Actor_MLP_action_p__1, 80*sizeof(char), NULL, 0);
		fifoPop(init_out__weights_in__0, FIFO_Head_Actor_MLP_action_p__0, 240*sizeof(char), NULL, 0);
		fifoPop(init_out__bias_in__1, FIFO_Head_Actor_MLP_action_p__3, 4*sizeof(char), NULL, 0);
		fifoPop(init_out__weights_in__1, FIFO_Head_Actor_MLP_action_p__2, 80*sizeof(char), NULL, 0);
		fifoPop(init_out__state_angular_in__0, FIFO_Head_broadcastState_end__0, 8*sizeof(char), NULL, 0);
		// Broadcast Actor_MLP_action_predictor_Hidden_layer_br_input
		{
			// memcpy #0
			memcpy(input_0_0__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_3__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_6__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_9__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_12__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_15__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_18__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_21__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_24__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_27__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_30__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_33__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_36__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_39__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_42__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_45__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_48__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_51__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_54__input__0+0, init_out__input__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(input_0_57__input__0+0, init_out__input__0+0, 3*sizeof(float));
		}
		weightsGen(20/*input_size*/,1/*layer_size*/,init_out__weights_in__1,init_out__bias_in__1,weights_out__weights_in__1,bias_out__bias_in__1); // Actor_MLP_action_predictor_weights_output_weightGen
		// Broadcast Actor_MLP_action_predictor_weights_output_BroadcastBiasGen
		{
			// memcpy #0
			memcpy(bias_out0_0_0__bias_values__1+0, bias_out__bias_in__1+0, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out1_1_0__end_in__0+0, bias_out__bias_in__1+0, 1*sizeof(float));
		}
		// Broadcast Actor_MLP_action_predictor_weights_output_BroadcastWeightsGen
		{
			// memcpy #0
			memcpy(weights_out1_0_0__end_in__1+0, weights_out__weights_in__1+0, 20*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_20_0__weights__0+0, weights_out__weights_in__1+0, 20*sizeof(float));
		}
		fifoPush(bias_out1_1_0__end_in__0, FIFO_Head_Actor_MLP_action_p__3, 4*sizeof(char), NULL, 0);
		weightsGen(3/*input_size*/,20/*layer_size*/,init_out__weights_in__0,init_out__bias_in__0,weights_out__weights_in__0,bias_out__bias_in__0); // Actor_MLP_action_predictor_weights_hidden_weightGen
		// Broadcast Actor_MLP_action_predictor_weights_hidden_BroadcastBiasGen
		{
			// memcpy #0
			memcpy(bias_out0_0_0__bias_values__0+0, bias_out__bias_in__0+0, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_1__bias_values__0+0, bias_out__bias_in__0+1, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_2__bias_values__0+0, bias_out__bias_in__0+2, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_3__bias_values__0+0, bias_out__bias_in__0+3, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_4__bias_values__0+0, bias_out__bias_in__0+4, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_5__bias_values__0+0, bias_out__bias_in__0+5, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_6__bias_values__0+0, bias_out__bias_in__0+6, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_7__bias_values__0+0, bias_out__bias_in__0+7, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_8__bias_values__0+0, bias_out__bias_in__0+8, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_9__bias_values__0+0, bias_out__bias_in__0+9, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_10__bias_values__0+0, bias_out__bias_in__0+10, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_11__bias_values__0+0, bias_out__bias_in__0+11, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_12__bias_values__0+0, bias_out__bias_in__0+12, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_13__bias_values__0+0, bias_out__bias_in__0+13, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_14__bias_values__0+0, bias_out__bias_in__0+14, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_15__bias_values__0+0, bias_out__bias_in__0+15, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_16__bias_values__0+0, bias_out__bias_in__0+16, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_17__bias_values__0+0, bias_out__bias_in__0+17, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_18__bias_values__0+0, bias_out__bias_in__0+18, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out0_0_19__bias_values__0+0, bias_out__bias_in__0+19, 1*sizeof(float));
			// memcpy #0
			memcpy(bias_out1_20_0__end_in__0+0, bias_out__bias_in__0+0, 20*sizeof(float));
		}
		// Broadcast Actor_MLP_action_predictor_weights_hidden_BroadcastWeightsGen
		{
			// memcpy #0
			memcpy(weights_out1_0_0__end_in__0+0, weights_out__weights_in__0+0, 60*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_0__weights__0+0, weights_out__weights_in__0+0, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_3__weights__0+0, weights_out__weights_in__0+3, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_6__weights__0+0, weights_out__weights_in__0+6, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_9__weights__0+0, weights_out__weights_in__0+9, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_12__weights__0+0, weights_out__weights_in__0+12, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_15__weights__0+0, weights_out__weights_in__0+15, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_18__weights__0+0, weights_out__weights_in__0+18, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_21__weights__0+0, weights_out__weights_in__0+21, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_24__weights__0+0, weights_out__weights_in__0+24, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_27__weights__0+0, weights_out__weights_in__0+27, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_30__weights__0+0, weights_out__weights_in__0+30, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_33__weights__0+0, weights_out__weights_in__0+33, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_36__weights__0+0, weights_out__weights_in__0+36, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_39__weights__0+0, weights_out__weights_in__0+39, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_42__weights__0+0, weights_out__weights_in__0+42, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_45__weights__0+0, weights_out__weights_in__0+45, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_48__weights__0+0, weights_out__weights_in__0+48, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_51__weights__0+0, weights_out__weights_in__0+51, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_54__weights__0+0, weights_out__weights_in__0+54, 3*sizeof(float));
			// memcpy #0
			memcpy(weights_out0_60_57__weights__0+0, weights_out__weights_in__0+57, 3*sizeof(float));
		}
		fifoPush(weights_out1_0_0__end_in__1, FIFO_Head_Actor_MLP_action_p__2, 80*sizeof(char), NULL, 0);
		fifoPush(bias_out1_20_0__end_in__0, FIFO_Head_Actor_MLP_action_p__1, 80*sizeof(char), NULL, 0);
		neuron(3/*input_size*/,input_0_0__input__0,weights_out0_60_0__weights__0,bias_out0_0_0__bias_values__0,output__input_0__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_0
		neuron(3/*input_size*/,input_0_3__input__0,weights_out0_60_3__weights__0,bias_out0_0_1__bias_values__0,output__input_1__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_1
		neuron(3/*input_size*/,input_0_30__input__0,weights_out0_60_30__weights__0,bias_out0_0_10__bias_values__0,output__input_10__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_10
		neuron(3/*input_size*/,input_0_33__input__0,weights_out0_60_33__weights__0,bias_out0_0_11__bias_values__0,output__input_11__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_11
		neuron(3/*input_size*/,input_0_36__input__0,weights_out0_60_36__weights__0,bias_out0_0_12__bias_values__0,output__input_12__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_12
		neuron(3/*input_size*/,input_0_39__input__0,weights_out0_60_39__weights__0,bias_out0_0_13__bias_values__0,output__input_13__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_13
		neuron(3/*input_size*/,input_0_42__input__0,weights_out0_60_42__weights__0,bias_out0_0_14__bias_values__0,output__input_14__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_14
		neuron(3/*input_size*/,input_0_45__input__0,weights_out0_60_45__weights__0,bias_out0_0_15__bias_values__0,output__input_15__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_15
		neuron(3/*input_size*/,input_0_48__input__0,weights_out0_60_48__weights__0,bias_out0_0_16__bias_values__0,output__input_16__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_16
		neuron(3/*input_size*/,input_0_51__input__0,weights_out0_60_51__weights__0,bias_out0_0_17__bias_values__0,output__input_17__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_17
		neuron(3/*input_size*/,input_0_54__input__0,weights_out0_60_54__weights__0,bias_out0_0_18__bias_values__0,output__input_18__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_18
		neuron(3/*input_size*/,input_0_57__input__0,weights_out0_60_57__weights__0,bias_out0_0_19__bias_values__0,output__input_19__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_19
		neuron(3/*input_size*/,input_0_6__input__0,weights_out0_60_6__weights__0,bias_out0_0_2__bias_values__0,output__input_2__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_2
		neuron(3/*input_size*/,input_0_9__input__0,weights_out0_60_9__weights__0,bias_out0_0_3__bias_values__0,output__input_3__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_3
		neuron(3/*input_size*/,input_0_12__input__0,weights_out0_60_12__weights__0,bias_out0_0_4__bias_values__0,output__input_4__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_4
		neuron(3/*input_size*/,input_0_15__input__0,weights_out0_60_15__weights__0,bias_out0_0_5__bias_values__0,output__input_5__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_5
		neuron(3/*input_size*/,input_0_18__input__0,weights_out0_60_18__weights__0,bias_out0_0_6__bias_values__0,output__input_6__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_6
		neuron(3/*input_size*/,input_0_21__input__0,weights_out0_60_21__weights__0,bias_out0_0_7__bias_values__0,output__input_7__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_7
		neuron(3/*input_size*/,input_0_24__input__0,weights_out0_60_24__weights__0,bias_out0_0_8__bias_values__0,output__input_8__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_8
		neuron(3/*input_size*/,input_0_27__input__0,weights_out0_60_27__weights__0,bias_out0_0_9__bias_values__0,output__input_9__0); // Actor_MLP_action_predictor_Hidden_layer_computeNeuron_9
		fifoPush(weights_out1_0_0__end_in__0, FIFO_Head_Actor_MLP_action_p__0, 240*sizeof(char), NULL, 0);
		// Join implode_Actor_MLP_action_predictor_Output_layer_computeNeuron_input
		{
			memcpy(output__input__0+0, output__input_0__0+0, 1*sizeof(float));
			memcpy(output__input__0+1, output__input_1__0+0, 1*sizeof(float));
			memcpy(output__input__0+2, output__input_2__0+0, 1*sizeof(float));
			memcpy(output__input__0+3, output__input_3__0+0, 1*sizeof(float));
			memcpy(output__input__0+4, output__input_4__0+0, 1*sizeof(float));
			memcpy(output__input__0+5, output__input_5__0+0, 1*sizeof(float));
			memcpy(output__input__0+6, output__input_6__0+0, 1*sizeof(float));
			memcpy(output__input__0+7, output__input_7__0+0, 1*sizeof(float));
			memcpy(output__input__0+8, output__input_8__0+0, 1*sizeof(float));
			memcpy(output__input__0+9, output__input_9__0+0, 1*sizeof(float));
			memcpy(output__input__0+10, output__input_10__0+0, 1*sizeof(float));
			memcpy(output__input__0+11, output__input_11__0+0, 1*sizeof(float));
			memcpy(output__input__0+12, output__input_12__0+0, 1*sizeof(float));
			memcpy(output__input__0+13, output__input_13__0+0, 1*sizeof(float));
			memcpy(output__input__0+14, output__input_14__0+0, 1*sizeof(float));
			memcpy(output__input__0+15, output__input_15__0+0, 1*sizeof(float));
			memcpy(output__input__0+16, output__input_16__0+0, 1*sizeof(float));
			memcpy(output__input__0+17, output__input_17__0+0, 1*sizeof(float));
			memcpy(output__input__0+18, output__input_18__0+0, 1*sizeof(float));
			memcpy(output__input__0+19, output__input_19__0+0, 1*sizeof(float));
		}
		neuron_output(20/*input_size*/,output__input__0,weights_out0_20_0__weights__0,bias_out0_0_0__bias_values__1,output__input_actions__0); // Actor_MLP_action_predictor_Output_layer_computeNeuron
		step(3/*state_space_size*/,1/*action_space_size*/,2/*state_angular_size*/,init_out__state_angular_in__0,state_angular_out__state__0,output__input_actions__0,state_observation__end_in__0); // Environment
		fifoPush(state_observation__end_in__0, FIFO_Head_Environment_end_st__0, 12*sizeof(char), NULL, 0);
		// Broadcast broadcastState
		{
			// memcpy #0
			memcpy(state_out0_0_0__state__0+0, state_angular_out__state__0+0, 2*sizeof(float));
			// memcpy #0
			memcpy(state_out1_2_0__end_in__0+0, state_angular_out__state__0+0, 2*sizeof(float));
		}
		fifoPush(state_out1_2_0__end_in__0, FIFO_Head_broadcastState_end__0, 8*sizeof(char), NULL, 0);
		renderEnv(2/*size*/,state_out0_0_0__state__0); // renderEnv
	}
}

