/**
 * @file main.c
 * @generated by InstrumentedCPrinter
 * @date Mon Mar 05 15:01:05 CET 2018
 *
 */

#define _GNU_SOURCE
#include <unistd.h>
#include <pthread.h>
#include <stdio.h>

// application dependent includes
#include "preesm.h"

// Declare computation thread functions
void *computationThread_Core0(void *arg);

pthread_barrier_t iter_barrier;
int stopThreads;

// setting a setting core affinity
int set_affinity_to_core(pthread_t* thread, int core_id) {
int num_cores = sysconf(_SC_NPROCESSORS_ONLN);
if (core_id < 0 || core_id >= num_cores)
  printf("Wrong core number %d\n", core_id);
  cpu_set_t cpuset;
  CPU_ZERO(&cpuset);
  CPU_SET(core_id, &cpuset);
  return pthread_setaffinity_np(*thread, sizeof(cpu_set_t), &cpuset);
}

int main(void)
{

  // Declaring thread pointers
  pthread_t threadCore0;

  #ifdef VERBOSE
  printf("Launched main\n");
  #endif

  // Creating a synchronization barrier
  stopThreads = 0;
  pthread_barrier_init(&iter_barrier, NULL, 1);

  communicationInit();

  // Creating threads
  pthread_create(&threadCore0, NULL, computationThread_Core0, NULL);
  set_affinity_to_core(&threadCore0,0);

  // Waiting for thread terminations
  pthread_join(threadCore0,NULL);

  #ifdef VERBOSE
  printf("Press any key to stop application\n");
  #endif

  return 0;
}

