
module mergeSS {
	typedef long parameter ;
	typedef long int ;
	interface loop {
		void mergeSS(in float scaleSpace0, in float scaleSpace1,
		in float scaleSpace2, in float scaleSpace3, 
		in float scaleSpace4, in float scaleSpace5,
		in float scaleSpace6, in float scaleSpace7,
		out float scaleSpace, in int O, in parameter S, in int octavesW, in int octavesH);
	} ;
} ;
