
module render {
	typedef long parameter ;
	typedef long int ;
	interface loop {
		void render (in parameter xSize, in parameter ySize, in char y_input,
			in int struct_x, in int struct_y, in int struct_o, in int struct_s, in float struct_ori, in int keyN,
			out char y_output, in float sigma, in parameter n_max) ;
	} ;
} ;
